# Flag Controller
ForumFlagList:
    pattern: /flag/list/
    defaults: { _controller: TeapotioForumBundle:Flag:list }

ForumFlagDelete:
    pattern: /flag/delete/{flagId}/
    defaults: { _controller: TeapotioForumBundle:Flag:delete }

ForumFlagIgnore:
    pattern: /flag/ignore/{flagId}/
    defaults: { _controller: TeapotioForumBundle:Flag:ignore }

# Moderation Controller
ForumModerationList:
    pattern: /moderation/list/
    defaults: { _controller: TeapotioForumBundle:Moderation:list }

# Board Controller
ForumNewBoard:
    pattern:  /new-board/
    defaults: { _controller: TeapotioForumBundle:Board:new }

ForumNewTopicWithoutBoard:
    pattern:  /new-topic/
    defaults: { _controller: TeapotioForumBundle:Topic:new }

ForumListBoards:
    pattern: /boards/
    defaults: { _controller: TeapotioForumBundle:Board:list }

ForumAdminPermissionsWithGroup:
    pattern: /admin/permissions/{groupId}/
    defaults: { _controller: TeapotioForumBundle:Admin:Permissions }

ForumAdminPermissions:
    pattern: /admin/permissions/
    defaults: { _controller: TeapotioForumBundle:Admin:Permissions }

ForumNewBoardInBoard:
    pattern:  /{boardSlug}/new-board/
    defaults: { _controller: TeapotioForumBundle:Board:new }
    requirements:
        boardSlug: .+?

ForumEditBoardPermissions:
    pattern:  /{boardSlug}/edit/permissions/
    defaults: { _controller: TeapotioForumBundle:Board:editPermissions }
    requirements:
        boardSlug: .+?

ForumTopicPin:
    pattern: /{boardSlug}/{topicSlug}-{topicId}/pin/
    defaults: { _controller: TeapotioForumBundle:Topic:pin }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"
        topicId:   \d+

ForumTopicLock:
    pattern: /{boardSlug}/{topicSlug}-{topicId}/lock/
    defaults: { _controller: TeapotioForumBundle:Topic:lock }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"
        topicId:   \d+

ForumTopicDelete:
    pattern: /{boardSlug}/{topicSlug}-{topicId}/delete/
    defaults: { _controller: TeapotioForumBundle:Topic:delete }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"
        topicId:   \d+

ForumTopicEdit:
    pattern: /{boardSlug}/{topicSlug}-{topicId}/edit/
    defaults: { _controller: TeapotioForumBundle:Topic:edit }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"
        topicId:   \d+

# Message Controller
ForumListMessagesByTopic:
    pattern: /{boardSlug}/{topicSlug}-{topicId}/
    defaults: { _controller: TeapotioForumBundle:Message:list }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"
        topicId:   \d+

ForumNewMessage:
    pattern: /{boardSlug}/{topicSlug}-{topicId}/new-message/
    defaults: { _controller: TeapotioForumBundle:Message:new }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"
        topicId:   \d+

ForumMessageEdit:
    pattern: /{boardSlug}/{topicSlug}-{topicId}/edit/{messageId}/
    defaults: { _controller: TeapotioForumBundle:Message:edit }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"
        topicId:   \d+
        messageId: \d+

ForumMessageFlag:
    pattern: /{boardSlug}/{topicSlug}-{topicId}/flag/{messageId}/
    defaults: { _controller: TeapotioForumBundle:Message:flag }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"
        topicId:   \d+
        messageId: \d+

ForumMessageDelete:
    pattern: /{boardSlug}/{topicSlug}-{topicId}/delete/{messageId}/
    defaults: { _controller: TeapotioForumBundle:Message:delete }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"
        topicId:   \d+
        messageId: \d+

ForumMessageStar:
    pattern: /{boardSlug}/{topicSlug}-{topicId}/star/{messageId}/
    defaults: { _controller: TeapotioForumBundle:Message:star }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"
        topicId:   \d+
        messageId: \d+

ForumMessageUnstar:
    pattern: /{boardSlug}/{topicSlug}-{topicId}/unstar/{messageId}/
    defaults: { _controller: TeapotioForumBundle:Message:unstar }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"
        topicId:   \d+
        messageId: \d+

ForumMessageReply:
    pattern: /{boardSlug}/{topicSlug}-{topicId}/reply/{messageId}/
    defaults: { _controller: TeapotioForumBundle:Message:reply }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"
        topicId:   \d+
        messageId: \d+

ForumMessageQuote:
    pattern: /{boardSlug}/{topicSlug}-{topicId}/quote/{messageId}/
    defaults: { _controller: TeapotioForumBundle:Message:quote }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"
        topicId:   \d+
        messageId: \d+

# Topic Controller
ForumListLatestTopics:
    pattern: /
    defaults: { _controller: TeapotioForumBundle:Topic:latest }

ForumEditBoard:
    pattern:  /{boardSlug}/edit/
    defaults: { _controller: TeapotioForumBundle:Board:edit }
    requirements:
        boardSlug: .+?

ForumDeleteBoard:
    pattern:  /{boardSlug}/delete/
    defaults: { _controller: TeapotioForumBundle:Board:delete }
    requirements:
        boardSlug: .+?

ForumMoveBoard:
    pattern:  /{boardSlug}/move/
    defaults: { _controller: TeapotioForumBundle:Board:move }
    requirements:
        boardSlug: .+?

ForumNewTopic:
    pattern: /{boardSlug}/new-topic/
    defaults: { _controller: TeapotioForumBundle:Topic:new }
    requirements:
        boardSlug: .+?

ForumListTopicsByBoard:
    pattern: /{boardSlug}/
    defaults: { _controller: TeapotioForumBundle:Topic:list }
    requirements:
        boardSlug: .+?
